services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf:/conf
      - ./nginx/certs:/certs
    ports:
      - "80:80"
      - "443:443"

  api:
    build: perspective-api
    ports:
      - "5000:5000"
